baseURL: "https://profile-johnchan.me/"
title: "Chia-Han Chan"

theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

params:
  description: "CHIA-HAN (John) CHAN — Computer Science undergraduate at National Yang Ming Chiao Tung University."
  author: John

  defaultTheme: light
  disableThemeToggle: true

  ShowShareButtons: false
  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true

  profileMode:
    enabled: false

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    style: autumn
